# Group definitions
- name: Install debian packages coming from group definitions
  package:
          name: "{{ packagesdebian }}"
          state: present
  when: packagesdebian is defined
- name: Remove debian packages coming from group definitions
  package:
          name: "{{ packagesdebian_absent }}"
          state: absent
  when: packagesdebian_absent is defined
# Host definitions
- name: Install debian packages coming from host definition
  package:
          name: "{{ packages_host }}"
          state: present
  when: packages_host is defined
- name: Remove debian packages coming from host definition
  package:
    name: "{{ packages_host_absent }}"
    state: absent
  when: packages_host_absent is defined
