# Group definitions
- name: Install packages coming from group definitions
  package:
          name: "{{ packagesfreebsd }}"
          state: present
  when: packages is defined
- name: Remove packages coming from group definitions
  package:
          name: "{{ packagesfreebsd_absent }}"
          state: absent
  when: packages_absent is defined
# Host definitions
- name: Install packages coming from host definition
  package:
          name: "{{ packages_host }}"
          state: present
  when: packages_host is defined
- name: Remove packages coming from host definition
  package:
    name: "{{ packages_host_absent }}"
    state: absent
  when: packages_host_absent is defined
