# Group definitions
- name: Install openwrt packages coming from group definitions
  package:
          name: "{{ packagesopenwrt }}"
          state: present
  when: packagesopenwrt is defined
- name: Remove openwrt packages coming from group definitions
  package:
          name: "{{ packagesopenwrt_absent }}"
          state: absent
  when: packagesopenwrt_absent is defined
# Host definitions
- name: Install openwrt packages coming from host definition
  package:
          name: "{{ packages_host }}"
          state: present
  when: packages_host is defined
- name: Remove openwrt packages coming from host definition
  package:
    name: "{{ packages_host_absent }}"
    state: absent
  when: packages_host_absent is defined
