# Group definitions
- name: Enable epel because without epel centos is nothing
  package:
    name: "epel-release"
    state: present
  when: ansible_distribution != "Fedora"
- name: Install redhat packages coming from group definitions
  package:
          name: "{{ packagesredhat }}"
          state: present
  when: packagesredhat is defined
- name: Remove redhat packages coming from group definitions
  package:
          name: "{{ packagesredhat_absent }}"
          state: absent
  when: packagesredhat_absent is defined
# Host definitions
- name: Install redhat packages coming from host definition
  package:
          name: "{{ packages_host }}"
          state: present
  when: packages_host is defined
- name: Remove redhat packages coming from host definition
  package:
    name: "{{ packages_host_absent }}"
    state: absent
  when: packages_host_absent is defined
